export const APP_ROUTE = {
  HOME_SCREEN: 'HOME_SCREEN' as 'HOME_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN' as 'SETTING_SCREEN',
};

export const AUTHENTICATION_ROUTE = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
};

export const MAIN_ROUTE = {
  HOME_TAB: 'HOME_TAB',
};
