const APP_ROUTE = {
  HOME_SCREEN: 'HOME_SCREEN',
};

const AUTHENTICATION_ROUTE = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
};

const MAIN_ROUTE = {
  HOME_TAB: 'HOME_TAB',
};

export {APP_ROUTE, AUTHENTICATION_ROUTE, MAIN_ROUTE};
